language: android
jdk: oraclejdk8
env:
android:
  components:
  - build-tools-29.0.2
  - android-29
  - sys-img-armeabi-v7a-addon-google_apis-google-25
script:
  - sudo chmod +x ./gradlew
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
